Demo content2
overture-stack/stage pull request #198
Opened 2024-04-09 13:15 UTC by MitchellShiell

Work in progress

2024-04-15 19:31 UTC, MitchellShiell commented on components/pages/about/ArticleComponent.tsx
> +	title?: string;
It's sort of a hack but if I want a title, text, image, **text, image**, then having the title optional allows me to do that with two article components back to back

2024-04-15 19:34 UTC, MitchellShiell commented on components/pages/about/ArticleComponent.tsx
> +	title?: string;
never ended up needing that actually, set back to mandatory

2024-04-15 19:52 UTC, ciaranschutte requested changes

2024-04-15 19:52 UTC, ciaranschutte commented on components/pages/about/index.tsx
> +			<div>{activeArticleId}</div>
this debugging line can be removed

2024-04-15 19:52 UTC, ciaranschutte commented on components/pages/about/index.tsx
> +	);
The "white gap error" you see when there are 3 elements nested in the `PageLayout` is due to CSS.
The parent element on the page has `display: grid; grid-template-rows: 50px 1fr 47px`.

ref: https://github.com/overture-stack/dms-ui/blob/develop/components/PageLayout.tsx


So it knows how to layout 3 rows of content. 
The page header is the 1st row, the main page content is the 2nd row and the footer is the 3rd row.
You can check this out using web inspector tools (let me know if I can point you to the exact location!)

When you add extra elements our "3 rows grid" doesn't know how to layout 4...5.. etc elements. only 3.
To fix - make 1 element to contain all the content eg. a div... now we're back to 3 elements.

2024-04-15 19:52 UTC, ciaranschutte commented on components/pages/about/index.tsx
> +	);
two really good resources for more on grid (don't let the cutesyness put you off, both really really good resources): https://cssgridgarden.com and https://www.joshwcomeau.com/css/interactive-guide-to-grid/

2024-04-15 20:01 UTC, ciaranschutte commented
as discussed offline, performance will be improved once compressed images are implemented

2024-04-16 18:38 UTC, MitchellShiell commented on components/pages/about/index.tsx
> +	);
Complete!

2024-04-17 19:52 UTC, ciaranschutte commented on tsconfig.json
> +		"components/pages/DocumentationContainerContainer"
Does this still exist?

2024-04-17 20:20 UTC, MitchellShiell commented on tsconfig.json
> +		"components/pages/DocumentationContainerContainer"
Nope!

2024-05-23 12:01 UTC, justincorrigible commented on components/pages/disclaimers/HeroComponent.tsx
> +import React, { ReactElement } from 'react';
We don't need to import React anymore
```suggestion
import { ReactElement } from 'react';
```

2024-05-23 12:02 UTC, justincorrigible commented on components/pages/disclaimers/notebox.tsx
> +import React, { ReactNode } from 'react';
```suggestion
import { ReactNode } from 'react';
```

2024-05-23 12:05 UTC, justincorrigible commented on pages/disclaimers/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
If we're creating new files, might well use the year that is done :)
```suggestion
 * Copyright (c) 2024 The Ontario Institute for Cancer Research. All rights reserved
```

2024-05-23 12:07 UTC, justincorrigible commented on components/pages/disclaimers/ArticleComponent.tsx
> +import React from 'react';
```suggestion
```

2024-07-10 20:13 UTC, closed without merging