WIP: Feat/55 load files
overture-stack/stage pull request #210
Opened 2024-09-10 17:40 UTC by demariadaniel

2024-09-16 19:01 UTC, demariadaniel commented
Pipeline failures require iobio-component version update

2024-09-17 19:06 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	const isDemoData = fileMetaData?.objectId === demoFileMetadata.objectId;
I've added a button to load the Demo File URL for short-term UI testing purposes

Our files currently hosted in Arranger/Stage are not loading properly and you see a lot of `NaN` on the charts

There are discrepancies between the demo files and expected BAM files (for example our demo files are only several hundred kB while the expected BAM files are multiple GB large)

This is a known issue that is being addressed btwn Bioinfo and the Iobio team, but is outside the scope of this ticket

I felt it made sense to include a 'Demo' button to validate the charts are working until we have updates

2024-09-17 20:24 UTC, joneubank commented on components/pages/explorer/BamTable.tsx
> +	const isDemoData = fileMetaData?.objectId === demoFileMetadata.objectId;
Are we doing sufficient error handling for cases where the BAM can't be processed as expected?

2024-09-17 20:40 UTC, joneubank requested changes

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/BamTable.tsx
> +	const [fileMetaData, setFileMetaData] = useState<FileMetaData | null>(null);
why `null` instead of `undefined`?

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
This is an async function that could be resolved after this component unmounts, or be triggered multiple times on re-renders. Does this useEffect function need to a return to cleanup?

https://blog.logrocket.com/understanding-react-useeffect-cleanup-function/

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/PageContent.tsx
> +	const [currentBamFile, setCurrentBamFile] = useState<FileTableData | null>(null);
why `null`

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/utils.tsx
> +};
Maybe these constants and shared types can be exported from a dedicated file, not this .tsx component?

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/utils.tsx
> +};
Should demo content be moved to a dedicated section of the file structure so that we can find it when needed, not hidden inside components that we want to be permanent?

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/utils.tsx
> +					`Error at getScoreDownloadUrls status: ${response.status}, ok: ${response.ok}`,
`response.ok` will always be false here.

2024-09-17 20:40 UTC, joneubank commented on components/pages/explorer/utils.tsx
Generic `utils` files are a pattern I would discourage. They become a dumping ground for all sorts of unknown things. Everything we export should have some utility ;)

Consider having seperate file for constants, file and file metadata types, Score utilities, common styles.

2024-09-17 20:44 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +};
They _are_ exported from a dedicated file but maybe that file doesn't need to be tsx, there's no React

2024-09-17 21:02 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +	};
mixing of styles - Promise vs await?
`await` and `then` are two distinct means to an end

2024-09-17 21:04 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
also needs to be awaited I think
likely have to do the `useEffect` inline function pattern

2024-09-17 21:04 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
needs `await`?

2024-09-17 21:12 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +		[loading, fileMetaData, elementState],
`fileMetaData` doesn't appear in this block, why is it a `useMemo` dependency?

2024-09-17 21:14 UTC, ciaranschutte commented on components/pages/explorer/PageContent.tsx
> +			if (!selectedBamFile) throw new Error('Selected file is not a compatible BAM or CRAM file');
prefer explicit adding brackets
```	
		if (!selectedBamFile) {throw new Error('Selected file is not a compatible BAM or CRAM file');}
```

2024-09-17 21:14 UTC, ciaranschutte commented on components/pages/explorer/PageContent.tsx
> +			} else if (!oneFileSelected) throw new Error('Only 1 BAM or CRAM file can be loaded');
a few cases of Error(s) being thrown... where are they being caught?

2024-09-17 21:16 UTC, ciaranschutte commented on components/pages/explorer/utils.tsx
> +		.then(async (response) => {
mixing of two diff paradigms `await` and `then`

2024-09-17 21:17 UTC, ciaranschutte commented on components/pages/explorer/utils.tsx
> +			return res as FileMetaData;
I think this can be typed without the need for `as`

2024-09-17 21:18 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +		[loading, fileMetaData, elementState],
It would be more explicitly `fileUrl` which is derived from `fileMetaData`

2024-09-17 21:19 UTC, ciaranschutte commented on components/pages/explorer/utils.tsx
> +			url: 'https://s3.amazonaws.com/iobio/NA12878/NA12878.autsome.bam',
not sure how much of a concern bandwith of this endpoint is, just to note it is a 187gb file in case there's cases of downloading it a lot while developing. eg. testing page that loads it on mount

2024-09-17 21:20 UTC, ciaranschutte commented on components/pages/explorer/index.tsx
> +						</TableContext.Consumer>
curious if there's a reason using the HOC way for context vs a hook?
I think we are consistently using hooks for the most part. would be good to keep with a pattern.

2024-09-17 21:24 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			if (!selectedBamFile) throw new Error('Selected file is not a compatible BAM or CRAM file');
Added

2024-09-17 21:25 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			} else if (!oneFileSelected) throw new Error('Only 1 BAM or CRAM file can be loaded');
Right now they're not. I'll review Stage implementation. However in future iterations this will be hidden behind a modal. The button would be disabled if incorrect options are selected. So I can update this to better reflect the design.

2024-09-17 21:26 UTC, ciaranschutte commented on components/pages/explorer/utils.tsx
> +		`;
can be a little cleaner like....

```
export const getToggleButtonStyles = (active: boolean, theme: Theme) => {
const {white, accent} = theme.colors;
return `
  background-color: ${active ? white: accent};
	color: ${active ? accent :  white};
`
}
```

2024-09-17 21:28 UTC, ciaranschutte commented on components/pages/explorer/PageContent.tsx
> +					return idMatch && isBamFile;
can likely combine `filter` calls

2024-09-17 21:29 UTC, ciaranschutte commented on components/pages/explorer/PageContent.tsx
> +				})[0];
if it's a big array and you're only looking for a single row Array.find might work better as it will stop once it finds a result

2024-09-17 21:59 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +		`;
Updated

2024-09-18 15:16 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	const [fileMetaData, setFileMetaData] = useState<FileMetaData | null>(null);
I've updated to use undefined combined w/ Ciaran's suggestion below to use .find()
Reviewing commits, null was an arbitrary choice at an earlier develop stage
I understand the semantic reasons for using undefined here

2024-09-18 15:17 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +	const [currentBamFile, setCurrentBamFile] = useState<FileTableData | null>(null);
Updated

2024-09-18 15:18 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +				})[0];
Updated to combine filters into a single .find()

2024-09-18 15:37 UTC, demariadaniel commented on components/pages/explorer/index.tsx
> +						</TableContext.Consumer>
No specific reason, I've updated to use a hook. In an earlier iteration I was not implementing the hook correctly so I used this as a workaround. Straightened out now: [useContext](https://github.com/overture-stack/stage/pull/210/commits/432a528c847c84979bb4e78d3a15e4808745ff7d)

2024-09-18 15:39 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +			url: 'https://s3.amazonaws.com/iobio/NA12878/NA12878.autsome.bam',
We've discussed potential bandwidth issues in the recurring Iobio meetings. Their team hasn't expressed any concerns so far but we're trying to keep it on radar.

2024-09-18 15:52 UTC, justincorrigible commented on components/pages/explorer/BamTable.tsx
> +	};
indeed, the await here doesn't seem to serve any purpose, for the awaited value is not used anywhere. Does this suggestion work the same? if so, there may be a better way to implement this whole segment, using React lifecycle methods.

```suggestion
	const loadAndSetFile = (file: FileTableData) => new Promise((resolve, reject) => {
		getFileMetaData(file).then((data) => {
			if (data) {
				setFileMetaData(data);
				setLoading(false);
				return resolve();
			}
			reject();
		});
	});
```

2024-09-18 15:54 UTC, justincorrigible commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
seeing the loadAndSetFile is a promise/async with side effects, I think this can all be better abstracted into a custom hook instead.

2024-09-18 15:59 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +				return false;
this line is not needed, since find only cares for `true`.
```suggestion
```

2024-09-18 16:00 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +				throw new Error('Selected file is not a compatible BAM or CRAM file');
are the errors thrown in this file being caught anywhere that produces visible feedback to the user? it's unclear here.

2024-09-18 16:24 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +	return await fetch(
in Stage, we prefer using Axios over `fetch`

2024-09-18 16:30 UTC, justincorrigible commented on components/pages/explorer/index.tsx
> +import { TableContext } from '@overture-stack/arranger-components/dist/';
unused, and we shouldn't import parts of Arranger that are not exported through the package root.
```suggestion
```

2024-09-18 16:35 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +import { UseTableContextProps } from '@overture-stack/arranger-components/dist/Table/types';
sounds like these need to be exported from Arranger's root. I'll put those in my todo:s

2024-09-18 18:01 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +				return false;
Removed

2024-09-18 18:30 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +	return await fetch(
Updated w/ changes to promise/await pattern mixing: 

[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)

2024-09-18 18:30 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +			return res as FileMetaData;
Removed

2024-09-18 18:31 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +		.then(async (response) => {
Updated to prefer promises w/ change to use Axios:

[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)

2024-09-18 18:32 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
Removed several async/awaits, see below comments

2024-09-18 18:32 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	};
[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)[Straighten out promise/await mix](https://github.com/overture-stack/stage/pull/210/commits/39050139ab248ae218887c4bfa5f452e76909768)

2024-09-18 18:33 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
Created files for `constants`, `fileTypes`, `fileUtils` and `getButtonStyles`

2024-09-18 18:33 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +					`Error at getScoreDownloadUrls status: ${response.status}, ok: ${response.ok}`,
Removed

2024-09-18 18:34 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
See comments, updated to use promises

2024-09-18 18:34 UTC, demariadaniel commented on components/pages/explorer/index.tsx
> +import { TableContext } from '@overture-stack/arranger-components/dist/';
Removed

2024-09-18 18:38 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +import { UseTableContextProps } from '@overture-stack/arranger-components/dist/Table/types';
I was able to update `useTableContext` but not `type UseTableContextProps`

2024-09-18 19:05 UTC, demariadaniel commented on components/pages/explorer/utils.tsx
> +};
Grouped all Demo related stuff in a block in the Table component

[Separate Demo Logic](https://github.com/overture-stack/stage/pull/210/commits/019988c6c8b005bfff9d77ec04710db246deb1c8)

2024-09-18 20:46 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
@demariadaniel Lots of good improvements here. Thank you.
I'm not 100% convinced on this `loadAndSetFile` function yet.

I think there's two things at play:
1) vanilla JS handling of async operations
How does this function know to wait on the async operation of `loadAndSetFile`?

2) Justins point of extracting to a hook. Which is _likely_ something along the lines of moving the conditional `if(!fileUrl & file)` into a dependency array for the custom hook. Keep in mind hooks shouldn't be called conditionally.

2024-09-23 12:49 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +	return Boolean((file as FileMetaData).objectId && (file as FileMetaData).parts[0].url);
Instinctively, as `file: any` is being used (not questioning that), since that means this function is not validating that the variable is set, seems like there's need to guard against missing values or properties so the code won't crash. curious to see if @joneubank would disagree on this one (for my own TS education)

```suggestion
	return Boolean((file as FileMetaData)?.objectId && (file as FileMetaData)?.parts?.[0]?.url);
```

2024-09-23 12:51 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +	const fileMetaData = getScoreDownloadUrls(selectedBamFile);
it's better practice to only instantiate/execute functions that have already been defined.

in this case, `getScoreDownloadUrls` is being defined a few lines after this one.

2024-09-23 12:56 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +			return response.data;
based on the condition you wrote in 61, this seems like a good use case for. "do not not ask negatives".

```suggestion
			if (response.status === 200) {
				return response.data;
			}
			
			throw new Error(`Error at getScoreDownloadUrls status: ${response.status}, ok: false`);
```

2024-09-23 12:57 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +			console.error(`Error at getScoreDownloadUrls with object_id ${object_id}`, error);
is this error handling sufficient? o just WIP? if so,best to add a comment/todo

2024-09-23 13:10 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +				Router.push({
is this version of nextjs so outdated that we don't have the useRouter hook available?
https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#userouter-hook

2024-09-23 13:14 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +			}
Isn't this condition chain equivalent to the following (simpler) suggestion?
```suggestion
			if (!oneFileSelected) {
				return Router.push({
					pathname: '/_error',
				});
			}
```

...asides from which, is this version of NextJS so outdated that we don't have the `useRouter` hook available?
https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#userouter-hook

2024-09-23 13:25 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +			if (selectedBamFile === undefined) {
think if we invert the previous condition to a positive (e.g. `if oneFileSelected`) then we can DRY all the error handling in the `else` scenario.

2024-09-23 15:54 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			const selectedBamFile = tableData.find((data) => {
Yes, I've changed it to `tableData` for now

2024-09-23 16:03 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +	const fileMetaData = getScoreDownloadUrls(selectedBamFile);
Moved

2024-09-23 16:12 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			if (selectedBamFile === undefined) {
There are 2 error scenarios here, a) you picked too many / too few files, b) the file you picked isn't compatible

Scenario A is now condensed to a single statement but there's still a second block to handle scenario B

2024-09-23 16:19 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +			return response.data;
Yep like that

2024-09-23 19:27 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +	return Boolean((file as FileMetaData).objectId && (file as FileMetaData).parts[0].url);
Updated

2024-09-23 19:41 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +			console.error(`Error at getScoreDownloadUrls with object_id ${object_id}`, error);
Sufficient in that the error stays console-bound rather than crashing the page.
We discussed offline that there is only generic error handling at this point in Stage. I've added a TODO comment for a later point when we update how we handle errors.

2024-09-23 21:01 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
I've refactored this again to prefer asyncs based on the pattern here:
https://devtrium.com/posts/async-functions-useeffect
Basically useEffect depends on async functions to call await and setState
I've updated these functions as well to use async everywhere, and to update error handling. You see an infinite loader for now if there's an error from Score, with errors in the console, but no error pop up.

I've tested this a few times and it seems to be working well with forced test errors and switching between application states.

2024-09-23 21:38 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	const isDemoData = fileMetaData?.objectId === demoFileMetadata.objectId;
There are errors related to iobio-charts which are known and we've asked them to fix. Some are logged in console, but there is an uncaught error on hover.
I've attempted to add a `componentDidCatch` to mitigate this but it's not working for me as expected.

All errors I can find related to Arranger / Score are handled by a console.error, so there should be nothing uncaught from that angle. Setup for UI displayed errors with messages needs further work on the Stage side.

2024-09-24 14:16 UTC, ciaranschutte commented on components/pages/explorer/PageContent.tsx
> +			}) as FileTableData | undefined;
is this needed if there's this https://github.com/overture-stack/stage/pull/210/files#diff-d22d109917820bd9b112220302d1f28113412fb3db7c40ada3d03d835f5aacc1R30 typeguard in use?

2024-09-24 14:21 UTC, ciaranschutte commented on components/pages/explorer/constants.ts
> +};
interesting note - these can be their actual types and not only strings because using `URLSearchParams` will format them correctly as needed

2024-09-24 18:48 UTC, justincorrigible commented on components/pages/explorer/fileUtils.ts
> +	}
past the if's return, there's no need for an else.

```suggestion
	}

	console.error(`Error at getScoreDownloadUrls with object_id ${object_id}`);
	throw new Error(`Error at getScoreDownloadUrls status: ${response.status}, ok: false`);
```

2024-09-24 21:26 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			}) as FileTableData | undefined;
It's because of .find, which returns `: unknown`

2024-09-24 21:35 UTC, demariadaniel commented on components/pages/explorer/constants.ts
> +};
Good idea but URLSearchParams is actually expecting `Record<string, string>`

2024-09-24 21:37 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +	}
Updated

2024-09-24 22:35 UTC, ciaranschutte commented on components/pages/explorer/constants.ts
> +};
Where is the type coming from?

I checked this works: 
```js
new URLSearchParams({ext: true, count: 8, x: 'a'}).toString()
```

also check 2nd example here: 
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#examples

2024-09-24 23:21 UTC, ciaranschutte commented on components/pages/explorer/fileUtils.ts
> +	const length = fileData.file?.size?.toString();
This is optional chaining 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
not nullish coalescing
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

and will potentially return `undefined` which does not have the `toString` method

2024-09-24 23:22 UTC, ciaranschutte commented on components/pages/explorer/fileUtils.ts
> +	const length = fileData.file?.size?.toString();
mentioning nullish coalescing because I think they're being confused in this PR https://github.com/overture-stack/stage/pull/210/commits/803ddabe19c7389cadd6ebe7cb33d9feaa233967

2024-09-25 03:23 UTC, ciaranschutte requested changes
few bits of React improvement:

regarding asyncs and this comment
https://github.com/overture-stack/stage/pull/210#discussion_r1772071160
I think you might need to follow the example down to this section in the link you shared: https://devtrium.com/posts/async-functions-useeffect#what-if-you-need-to-extract-the-function-outside-useeffect

smaller ones:
- nested components not needed
- no need for useMemo
- static vars inside components


---
looks like the core bit of state we care about is the `fileUrl` so my gut is telling me that there's improvements we could make in computed that but I don't have bandwidth for that right now. I imagine it's along the lines of just passing in a `fileUrl` and `loading` props to the BamTable and leaving the reasoning about files somewhere else.

2024-09-25 03:23 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
this is still calling an async function without await

2024-09-25 03:23 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +	};
move out of component

2024-09-25 14:09 UTC, demariadaniel commented on components/pages/explorer/constants.ts
> +};
<img width="643" alt="Screenshot 2024-09-25 at 10 09 09 AM" src="https://github.com/user-attachments/assets/b885456f-b07a-4293-9805-19665ec1a89d">

<img width="645" alt="Screenshot 2024-09-25 at 10 08 41 AM" src="https://github.com/user-attachments/assets/b1216235-a038-4bd9-84d8-556b68d64b82">

2024-09-25 14:28 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	);
I will revisit React / code quality comments. To clarify:
This is a feature branch deployed to its own URL on a project that is deprioritized for the next 3-6 months due to project scheduling requirements.

Demo specific code is provided due to the fact that the files currently hosted in Song/Arranger are not working with the Iobio server. This is a data compatibility issue that needs additional troubleshooting. 

The Demo code is there to facilitate short term UI testing while the data issues are resolved. Without an option to load the demo data the Visualization page displays multiple `NaN` and blank graphs. So without the Demo data there's no testing the Iobio 'happy path', which does work.

I've been asked to move off this project temporarily so without time to devote to solving this properly I've added a temporary solution to enable other team members to continue working.

2024-09-25 14:50 UTC, demariadaniel commented on components/pages/explorer/constants.ts
> +};
Errors when updating types/values as described

2024-09-25 14:58 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	};
Moved: [Move Demo Data to its own file](https://github.com/overture-stack/stage/pull/210/commits/fddb1264fffc7123d43b3043835f2dd4ca8a7df1)

I was trying to centralize all Demo Data logic so that removal wouldn't require scouring several places, see discussion here:
https://github.com/overture-stack/stage/pull/210#discussion_r1763983157

Because the Demo Data logic relies on hooks and state in the parent component I had it all grouped in one block with the understanding it was only temporary.

I've moved the Component and metadata constant so they are not constantly redeclared but the remaining logic is still tied to the parent component.

2024-09-25 15:00 UTC, demariadaniel commented on global/config.ts
> +		NEXT_PUBLIC_SCORE_API_URL: publicConfig.NEXT_PUBLIC_SCORE_API_URL,
Added

2024-09-25 15:01 UTC, ciaranschutte commented on components/pages/explorer/BamTable.tsx
> +	};
I'd ask what about `demoFileMetadata` is tied to a hook or state? It looks like a regular object with static property values.

2024-09-25 15:05 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
>  	return useMemo(
It's used in both PageContent (parent) and RepoTable (sibling) components so I was following the pattern and waiting to see if it drew people's ire ;) 
Removed

2024-09-25 15:05 UTC, demariadaniel commented
Missing await added: [Add missing await](https://github.com/overture-stack/stage/pull/210/commits/7cec0c6a014822105dae83ca875f96daa5f810dd)

@ciaranschutte re: https://github.com/overture-stack/stage/pull/210#discussion_r1774354050

2024-09-25 15:06 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	);
moved: https://github.com/overture-stack/stage/pull/210#discussion_r1775406238

2024-09-25 15:08 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
>  	const [elementState, toggleElementState] = useState(initElementState);
Fair, at the moment there are only two states which is why I used `toggle` but I guess `setElementState` is correct both now and in the future

2024-09-25 15:18 UTC, justincorrigible commented on .env.schema
> +
Thinking this may be useful for future reference later
```suggestion
// Score file access is needed for IOBIO and jBrowse components. This variable is not needed in vanilla Stage or Arranger
```

2024-09-25 15:26 UTC, demariadaniel commented on .env.schema
> +
Added

2024-09-25 16:03 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +const BamTable = ({ file }: { file: FileTableData | undefined }) => {
You are correct that is what happens. Right now this is managed by disabling the files/visualization button when the bamFile is undefined. There is no URL management for bamFile selected or FileTable/BamTable. File is undefined on page load.

2024-09-25 16:32 UTC, demariadaniel commented on components/pages/explorer/fileUtils.ts
> +};
OK - axios was throwing an error, but it was printing to console, and not reading these lines.
I've straightened this out with Axios promise/then/catch. Errors yield infinite loading state.

2024-09-27 14:41 UTC, demariadaniel commented on components/pages/explorer/PageContent.tsx
> +			}) as FileTableData | undefined;
Updated in [33629a4](https://github.com/overture-stack/stage/pull/210/commits/33629a48f7de14310209ef0e538dfd1d50b007d2)

As discussed on Slack the .filter `as` would ideally not be needed but something about the type guard `rowIsFileData` isn't working quite as intended.

2024-09-27 14:52 UTC, demariadaniel commented on components/pages/explorer/constants.ts
> +};
Checked this again and seeing these same errors using the example you provided so this is a good one to compare notes on

2024-09-27 14:53 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +			loadAndSetFile(file);
Updated

2024-09-27 15:30 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	};
Excellent - moved everything into the Demo Button component. Just needed a day to sleep on it.
There's some logic to manage switching from the Demo file back to a real file that needed untangling but it should be figured out now.

2024-09-27 15:30 UTC, demariadaniel commented on components/pages/explorer/BamTable.tsx
> +	};
[5872309](https://github.com/overture-stack/stage/pull/210/commits/587230919753f7c7882c868b63e37c211e81332b)

2024-09-27 23:43 UTC, ciaranschutte approved these changes
offline discussion of context of this feature branch - we are good to approve as is and improve upon later

2024-09-30 13:47 UTC, merged