Stage Dev Documentation
overture-stack/stage pull request #212
Opened 2024-10-09 01:01 UTC by MitchellShiell

The branch is linked and rendered on a [single, easy-to-navigate developer hub](https://main--overturedev.netlify.app/) that beautifully renders all our product documentation from the `/docs` folder of all our GitHub repositories.

- [x] An updated **`Readme.md`** file.
- [x] A **`/docs`** folder with the following basic structure:
   
```
.
├── /overview
└── /setup
```

   Usage will be added next (but not included in this round of review)

- [x] An updated **`contributing`** file
- [x] An updated **`code_of_conduct`** file
- [x] An updated **`license.md`** file

> [!IMPORTANT]  
> Before going live will need to update any links to the demo discussion board and Netlify deploy preview

## 🫵 To Review

- [x] [Overview page](https://main--overturedev.netlify.app/docs/core-software/stage/overview/)
    - I require input filling in the descriptions for the [repository structure section](https://main--overturedev.netlify.app/docs/Core-Software/stage/overview#repository-structure)
- [ ] [Setup page](https://main--overturedev.netlify.app/docs/Core-Software/stage/setup)

2024-10-09 21:09 UTC, demariadaniel commented on docs/setup.md
> +   ![Stage Dev](./assets/stageDev.svg 'Stage Dev Environment')
Same image is used in Overview so I'm wondering whether if it's really needed twice?

2024-10-09 21:10 UTC, demariadaniel commented on docs/setup.md
> +    :::info
I'm not sure this is formatted correctly, in Github Markdown preview it just shows as text :::info

2024-10-09 21:11 UTC, MitchellShiell commented on docs/setup.md
> +    :::info
On the fence with these, they render on docusaurus nicely but are a little cumbersome when reading the markdown: https://docusaurus.io/docs/markdown-features/admonitions

2024-10-09 21:11 UTC, demariadaniel commented on docs/setup.md
> +    :::tip
Similar issue here to :::info above

2024-10-09 21:12 UTC, demariadaniel commented on docs/setup.md
> +:::warning
Same as :::tip and :::warning, not sure the formatting is correct here

2024-10-09 21:16 UTC, demariadaniel commented on docs/setup.md
> +    :::tip
I see, it's a mismatch between Docusaurus and GitHub

2024-10-09 21:29 UTC, demariadaniel commented on docs/overview.md
> +├── /global
/global
-/hooks
-/utils

2024-10-16 14:26 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
**Components**: UI elements and tools used to compose Pages and features throughout the application. Includes standardized reusable elements for navigation, page structure, error states and theming, plus page-specific features.

2024-10-16 14:44 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
**Pages**: The central location for the main application file and all page routes, based on Next.js Pages Routing system: https://nextjs.org/docs/pages/building-your-application/routing
Contains the root `_app.jsx` file and individual folders/files for each navigable page in the site. Implements code found in `/global` and `/components`.

2024-10-16 14:45 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
**Public**: Static public assets such as SVGs and other images.

2024-10-16 14:47 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
cc: @justincorrigible Let me know how would you expand / edit these sections in `overview.md`

2024-10-16 14:47 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
**Tests**: Unit tests built in Jest for insuring code stability.

2024-10-16 14:49 UTC, demariadaniel commented on docs/overview.md
> +[Explaination]
@MitchellShiell Tests and Public are extremely minimal in the codebase, and also extremely common in any codebase, so these descriptions are pretty short.

2024-11-25 19:29 UTC, demariadaniel requested changes
One misspelling and a question about duplicate links

2024-11-25 19:33 UTC, MitchellShiell commented on README.md
> +- [**Common Usage Docs**](https://docs.overture.bio/docs/core-software/Stage/setup)
Good catch, fixed

2024-11-25 19:34 UTC, MitchellShiell commented on README.md
> +- [**Setting up the Development Enviornment**](https://docs.overture.bio/docs/core-software/Stage/setup)
I will be forever at war with spelling environment, fixed

2024-11-25 20:10 UTC, demariadaniel approved these changes
LGTM 📖 📚

2024-11-26 17:53 UTC, justincorrigible commented on README.md
> +- **Global:** Global: Utilities, definitions and configuration related to core processes for running the application, or used widely throughout the app. Covers functionality such as authentication &
duplication by likely mistake?
```suggestion
- **Global:** Utilities, definitions and configuration related to core processes for running the application, or used widely throughout the app. Covers functionality such as authentication & authorization, environment & context sharing, URL management and Page construction.
```

2024-11-26 17:54 UTC, justincorrigible commented on README.md
> +- **Public:** Static public assets such as SVGs and other images.
superfluous
```suggestion
- **Public:** Static assets such as SVGs and other images used by the interface.
```

2024-11-26 18:41 UTC, justincorrigible commented on code_of_conduct.md
not sure how I feel about having the same markdown files duplicated over an over across all repos, when they can all be distributed org-wide from the .github repo instead.

for reference: https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/

2024-11-26 18:42 UTC, justincorrigible commented on docs/assets/addStageScreenshot
placeholder?

2024-11-26 18:48 UTC, justincorrigible commented on README.md
> +## Repository Structure
I think this section ought just link to the overview docs, rather than duplicate the text.
easier to maintain and prevents communication issues.

2024-11-26 18:54 UTC, justincorrigible commented on docs/overview.md
> +- **Public:** Static public assets such as SVGs and other images.
```suggestion
- **Public:** Static assets such as SVGs and other images used by the interface.
```

2024-11-26 18:59 UTC, justincorrigible requested changes
great work overall. all the user documentation is looking amazing across Overture! 👏 
left a couple suggestions, and as always would be open to discuss if you disagree with anything!

unrelated note: rebased the branch to bring some pipeline changes, seeking to fix the failing build checks (edit: it worked)

2024-11-26 21:40 UTC, MitchellShiell commented on README.md
> +## Repository Structure
mismatching communication issues is valid, I'll update this accordingly

2024-11-26 21:42 UTC, MitchellShiell commented on code_of_conduct.md
Ah i see what you mean, remove code of conduct from the repos and let the .github do its magic,

2024-11-26 21:44 UTC, MitchellShiell commented on docs/assets/addStageScreenshot
Good catch

2025-02-05 21:26 UTC, justincorrigible approved these changes

2025-02-05 21:41 UTC, merged